### ISSUE TITLE
gulp update should fetch changes concurrently in all repositories

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-env#19]
Moved from https://github.com/ckeditor/ckeditor5/issues/213.

**Comment by pomek** [comment]
I tried to do something related to this topic.

First what I wanted to do was make the `tools.shExec` method (from `@ckeditor/ckeditor5-dev-utils`) asynchronous.

```js
shExec( command, options = { verbosity: 'info' } ) {
	const sh = require( 'shelljs' );
	sh.config.silent = true;

	return new Promise( ( resolve, reject ) => {
		sh.exec( command, ( code, stdout, stderr ) => {
			const response = { code, stdout, stderr };

			if ( code ) {
				return reject( response );
			}

			return resolve( response );
		} );
	} );
},
```

It works well. Given task is called asynchronous. 

For example, task: `gulp exec --task sh --cmd "echo 1; sleep 2; echo 2;"` was executed through 2 secs. Not an asynchronous version of `shExec`, the same task executed through ~40 secs.

Unfortunately, the next big issue occurs when we want to log something during the task. For example, `gulp update` logs a lot of messages during the update (it logs when git fetch, git pull, etc).

When the asynchronous task is executed, the console looks like:

```
[11:19:27] Starting 'update'...
[11:19:27] Fetching branches from ckeditor5...
[11:19:27] Fetching branches from ckeditor5-autoformat...
[11:19:27] Checking out ckeditor5-autoformat to master...
// Here should be an output for the `git checkout master` command
[11:19:27] Pulling changes to ckeditor5-autoformat...
// Here should be an output for the `git pull` command
```

Because all tasks are asynchronous, all logs can be mixed and unreadable. 

We need to figure out how to collect logs from a particular repository. After executing the task on the particular repository, we will display the collected logs.

**Comment by Reinmar** [comment]
The best way to manage when something gets logged to the console would be to pass a logger instance to the `shExec()` function and implement a stack + flush functionality in the logger. Then, the task would be able to pass a separate logger instances to each directories' processes and log once a certain process is done.

This may sound like a bit of overengineering, but shExec wraps a good piece of logging logic which should not be spread over the whole codebase. Hence, the potentially easier solution such as allowing passing a callback to `shExec` and handling output in that callback would be badly against DRY.

**Comment by Reinmar** [comment]
Anyway, making `gulp update` faster would be nice, but the effort needed to do that is too big. So we'll have to live with it.

**Comment by Reinmar** [comment]
There's perhaps one thing that we could improve:

```js
				log.info( `Fetching branches from ${ urlInfo.name }...` );
				git.fetchAll( repositoryAbsolutePath );

				log.info( `Checking out ${ urlInfo.name } to ${ urlInfo.branch }...` );
				git.checkout( repositoryAbsolutePath, urlInfo.branch );

				log.info( `Pulling changes to ${ urlInfo.name }...` );
				git.pull( repositoryAbsolutePath, urlInfo.branch );
```

This code does fetch twice. Unfortunately, I'm not sure how to do "pull without fetch" reliably (to not change this code's behaviour). Is it just `git merge origin`? What if branch doesn't have a remote tracking branch set? Is it possible?

**Comment by pomek** [comment]
Moved to https://github.com/ckeditor/ckeditor5-dev/issues/14.
